authorization-server:
  security:
    max-login-attempts: ${MAX_LOGIN_ATTEMPTS}
eureka:
  client:
    register-with-eureka: false
spring:
  application:
    name: authorization-server
  data:
    web:
      pageable:
        default-page-size: 10
    rest:
      base-path: /rest/api
  datasource:
    driver-class-name: org.postgresql.Driver
    flyway:
      url: ${spring.datasource.jdbc-url}
      user: ${PSQL_FLYWAY_USERNAME:${spring.datasource.username}}
      password: ${PSQL_FLYWAY_PASSWORD:${spring.datasource.password}}
    jdbc-url: ${PSQL_DATASOURCE_JDBC_URL}
    username: ${PSQL_DATASOURCE_USERNAME}
    password: ${PSQL_DATASOURCE_PASSWORD}
  jackson:
    date-format: dd.MM.yyyy HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
server:
  address: ${OAUTH2_SERVER_URL}
  port: ${SERVER_PORT}